version: "3"
services:
  delivr:
    build:
      context: .
    ports:
      - "8003:8002"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always
    networks:
      - vet
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: kimutai
      POSTGRES_PASSWORD: kimutai
      POSTGRES_DB: munchies

    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: always

    networks:
      - delivr

volumes:
  postgres_data:

networks:
  delivr:
    external: false
